// <auto-generated />
using System;
using BingoAdmin.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BingoAdmin.Infra.Migrations
{
    [DbContext(typeof(BingoContext))]
    [Migration("20251125170124_UpdateFullSchema")]
    partial class UpdateFullSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Bingo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartelasPorCombo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataInicioPrevista")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeCombos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioCriadorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCriadorId");

                    b.ToTable("Bingos");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Cartela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BingoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComboId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GridNumeros")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashUnico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroCartelaNoCombo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComboId");

                    b.ToTable("Cartelas");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Combo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BingoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataConfirmacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeDono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroCombo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BingoId");

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Ganhador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartelaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVencedorFinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RodadaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartelaId");

                    b.HasIndex("RodadaId");

                    b.ToTable("Ganhadores");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Padrao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPredefinido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mascara")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Padroes");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.PedraMaiorSorteio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GanhadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroSorteado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdemSorteio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RodadaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GanhadorId");

                    b.ToTable("PedraMaiorSorteios");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Rodada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BingoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EhRodadaExtra")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroOrdem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PadraoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPremio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BingoId");

                    b.HasIndex("PadraoId");

                    b.ToTable("Rodadas");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Sorteio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BingoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BolasSorteadas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataHoraFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("RodadaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RodadaId");

                    b.ToTable("Sorteios");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Bingo", b =>
                {
                    b.HasOne("BingoAdmin.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("UsuarioCriadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Cartela", b =>
                {
                    b.HasOne("BingoAdmin.Domain.Entities.Combo", "Combo")
                        .WithMany("Cartelas")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Combo", b =>
                {
                    b.HasOne("BingoAdmin.Domain.Entities.Bingo", "Bingo")
                        .WithMany("Combos")
                        .HasForeignKey("BingoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bingo");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Ganhador", b =>
                {
                    b.HasOne("BingoAdmin.Domain.Entities.Cartela", "Cartela")
                        .WithMany()
                        .HasForeignKey("CartelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BingoAdmin.Domain.Entities.Rodada", "Rodada")
                        .WithMany("Ganhadores")
                        .HasForeignKey("RodadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cartela");

                    b.Navigation("Rodada");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.PedraMaiorSorteio", b =>
                {
                    b.HasOne("BingoAdmin.Domain.Entities.Ganhador", "Ganhador")
                        .WithMany()
                        .HasForeignKey("GanhadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ganhador");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Rodada", b =>
                {
                    b.HasOne("BingoAdmin.Domain.Entities.Bingo", "Bingo")
                        .WithMany("Rodadas")
                        .HasForeignKey("BingoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BingoAdmin.Domain.Entities.Padrao", "Padrao")
                        .WithMany()
                        .HasForeignKey("PadraoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bingo");

                    b.Navigation("Padrao");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Sorteio", b =>
                {
                    b.HasOne("BingoAdmin.Domain.Entities.Rodada", "Rodada")
                        .WithMany("Sorteios")
                        .HasForeignKey("RodadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rodada");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Bingo", b =>
                {
                    b.Navigation("Combos");

                    b.Navigation("Rodadas");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Combo", b =>
                {
                    b.Navigation("Cartelas");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Rodada", b =>
                {
                    b.Navigation("Ganhadores");

                    b.Navigation("Sorteios");
                });
#pragma warning restore 612, 618
        }
    }
}
