// <auto-generated />
using System;
using BingoAdmin.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BingoAdmin.Infra.Migrations
{
    [DbContext(typeof(BingoContext))]
    [Migration("20260105210529_UpdateUsuarioSchema")]
    partial class UpdateUsuarioSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Bingo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartelasPorCombo")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInicioPrevista")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ModoPadroesDinamicos")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadeCombos")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeRodadas")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioCriadorId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPorCombo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCriadorId");

                    b.ToTable("Bingos");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.BingoPadrao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BingoId")
                        .HasColumnType("int");

                    b.Property<bool>("FoiSorteado")
                        .HasColumnType("bit");

                    b.Property<int>("PadraoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BingoId");

                    b.HasIndex("PadraoId");

                    b.ToTable("BingoPadroes");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Cartela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BingoId")
                        .HasColumnType("int");

                    b.Property<int>("ComboId")
                        .HasColumnType("int");

                    b.Property<string>("GridNumeros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroCartelaNoCombo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComboId");

                    b.ToTable("Cartelas");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Combo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BingoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataConfirmacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeDono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroCombo")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pagamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BingoId");

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.DesempateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BingoId")
                        .HasColumnType("int");

                    b.Property<int>("CartelaId")
                        .HasColumnType("int");

                    b.Property<int>("CartelaNumero")
                        .HasColumnType("int");

                    b.Property<int>("Combo")
                        .HasColumnType("int");

                    b.Property<bool>("IsVencedor")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PedraMaior")
                        .HasColumnType("int");

                    b.Property<int>("RodadaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DesempateItens");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BingoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Ganhador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartelaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVencedorFinal")
                        .HasColumnType("bit");

                    b.Property<int>("RodadaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartelaId");

                    b.HasIndex("RodadaId");

                    b.ToTable("Ganhadores");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Padrao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPredefinido")
                        .HasColumnType("bit");

                    b.Property<string>("Mascara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Padroes");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.PedraMaiorSorteio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GanhadorId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroSorteado")
                        .HasColumnType("int");

                    b.Property<int>("OrdemSorteio")
                        .HasColumnType("int");

                    b.Property<int>("RodadaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GanhadorId");

                    b.ToTable("PedraMaiorSorteios");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Rodada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BingoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EhRodadaExtra")
                        .HasColumnType("bit");

                    b.Property<int?>("MaximoGanhadores")
                        .HasColumnType("int");

                    b.Property<bool>("ModoPadroesDinamicos")
                        .HasColumnType("bit");

                    b.Property<int>("NumeroOrdem")
                        .HasColumnType("int");

                    b.Property<int?>("PadraoId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoJogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPremio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BingoId");

                    b.HasIndex("PadraoId");

                    b.ToTable("Rodadas");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.RodadaPadrao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("FoiSorteado")
                        .HasColumnType("bit");

                    b.Property<int>("PadraoId")
                        .HasColumnType("int");

                    b.Property<int>("RodadaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PadraoId");

                    b.HasIndex("RodadaId");

                    b.ToTable("RodadaPadroes");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Sorteio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BingoId")
                        .HasColumnType("int");

                    b.Property<string>("BolasSorteadas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataHoraFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("RodadaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RodadaId");

                    b.ToTable("Sorteios");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataValidadeLicenca")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLogado")
                        .HasColumnType("bit");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusAssinatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Bingo", b =>
                {
                    b.HasOne("BingoAdmin.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany()
                        .HasForeignKey("UsuarioCriadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.BingoPadrao", b =>
                {
                    b.HasOne("BingoAdmin.Domain.Entities.Bingo", "Bingo")
                        .WithMany("BingoPadroes")
                        .HasForeignKey("BingoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BingoAdmin.Domain.Entities.Padrao", "Padrao")
                        .WithMany()
                        .HasForeignKey("PadraoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bingo");

                    b.Navigation("Padrao");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Cartela", b =>
                {
                    b.HasOne("BingoAdmin.Domain.Entities.Combo", "Combo")
                        .WithMany("Cartelas")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Combo", b =>
                {
                    b.HasOne("BingoAdmin.Domain.Entities.Bingo", "Bingo")
                        .WithMany("Combos")
                        .HasForeignKey("BingoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bingo");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Ganhador", b =>
                {
                    b.HasOne("BingoAdmin.Domain.Entities.Cartela", "Cartela")
                        .WithMany()
                        .HasForeignKey("CartelaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BingoAdmin.Domain.Entities.Rodada", "Rodada")
                        .WithMany("Ganhadores")
                        .HasForeignKey("RodadaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cartela");

                    b.Navigation("Rodada");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.PedraMaiorSorteio", b =>
                {
                    b.HasOne("BingoAdmin.Domain.Entities.Ganhador", "Ganhador")
                        .WithMany()
                        .HasForeignKey("GanhadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ganhador");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Rodada", b =>
                {
                    b.HasOne("BingoAdmin.Domain.Entities.Bingo", "Bingo")
                        .WithMany("Rodadas")
                        .HasForeignKey("BingoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BingoAdmin.Domain.Entities.Padrao", "Padrao")
                        .WithMany()
                        .HasForeignKey("PadraoId");

                    b.Navigation("Bingo");

                    b.Navigation("Padrao");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.RodadaPadrao", b =>
                {
                    b.HasOne("BingoAdmin.Domain.Entities.Padrao", "Padrao")
                        .WithMany()
                        .HasForeignKey("PadraoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BingoAdmin.Domain.Entities.Rodada", "Rodada")
                        .WithMany("RodadaPadroes")
                        .HasForeignKey("RodadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Padrao");

                    b.Navigation("Rodada");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Sorteio", b =>
                {
                    b.HasOne("BingoAdmin.Domain.Entities.Rodada", "Rodada")
                        .WithMany("Sorteios")
                        .HasForeignKey("RodadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rodada");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Bingo", b =>
                {
                    b.Navigation("BingoPadroes");

                    b.Navigation("Combos");

                    b.Navigation("Rodadas");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Combo", b =>
                {
                    b.Navigation("Cartelas");
                });

            modelBuilder.Entity("BingoAdmin.Domain.Entities.Rodada", b =>
                {
                    b.Navigation("Ganhadores");

                    b.Navigation("RodadaPadroes");

                    b.Navigation("Sorteios");
                });
#pragma warning restore 612, 618
        }
    }
}
